config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :promocions
  resources :llamadas
  resources :categorias
  resources :negocios
  resources :vendedors
  resources :venta
  resources :entrevistas
  resources :version_negocios

  root 'inicio#opciones'

  get 'inicio/opciones'

  get 'users/index'

  post 'users/new'

  post 'users/create'

  get 'rechazados/users'

  get 'rechazados/negocios'

  get 'rechazados/promociones'

  get 'pendientes/rechazados'

  get 'pendientes/index'

  get 'entrevistas/index'

  get 'entrevistas/new'

  get 'version_negocios/index'

  get 'version_negocios/destroy'


end

app/models/promocion.rb
class Promocion < ApplicationRecord
  belongs_to :negocio
end

app/controllers/promocions_controller.rb
class PromocionsController < ApplicationController
  before_action :set_promocion, only: [:show, :edit, :update, :destroy]

  # GET /promocions
  # GET /promocions.json
  def index
    @promocions = Promocion.all
  end

  # GET /promocions/1
  # GET /promocions/1.json
  def show
  end

  # GET /promocions/new
  def new
    @promocion = Promocion.new
  end

  # GET /promocions/1/edit
  def edit
  end

  # POST /promocions
  # POST /promocions.json
  def create
    @promocion = Promocion.new(promocion_params)

    respond_to do |format|
      if @promocion.save
        format.html { redirect_to @promocion, notice: 'Promocion was successfully created.' }
        format.json { render :show, status: :created, location: @promocion }
      else
        format.html { render :new }
        format.json { render json: @promocion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promocions/1
  # PATCH/PUT /promocions/1.json
  def update
    respond_to do |format|
      if @promocion.update(promocion_params)
        format.html { redirect_to @promocion, notice: 'Promocion was successfully updated.' }
        format.json { render :show, status: :ok, location: @promocion }
      else
        format.html { render :edit }
        format.json { render json: @promocion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promocions/1
  # DELETE /promocions/1.json
  def destroy
    @promocion = Promocion.find(params[:id])
    @promocion.destroy
    respond_to do |format|
      format.html { redirect_to promocions_url, notice: 'Promocion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promocion
      @promocion = Promocion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promocion_params
      params.require(:promocion).permit(:nombre, :descripcion, :aprobada, :poster, :fecha_registro, :negocio_id)
    end
end

app/views/promocions/_form.html.erb
<center style="padding-top: 40px;">
<%= form_with(model: promocion, local: true) do |form| %>
  <% if promocion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(promocion.errors.count, "error") %> prohibited this promocion from being saved:</h2>

      <ul>
      <% promocion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field row" style="width: 40%; padding: 15px;">
    <div class="col-md-6" style="left: -124px;"><%= form.label :nombre %></div>
    <div class="col-md-6"><%= form.text_field :nombre, id: :promocion_nombre%></div>
  </div>

  <div class="field row" style="width: 40%; padding: 15px;">
    <div class="col-md-6" style="left: -105px;"><%= form.label :descripcion %></div>
    <div class="col-md-6"><%= form.text_field :descripcion, id: :promocion_descripcion %></div>
  </div>

  <label style="padding: 20px;">Desmarque si quiere dar de Baja</label>
  <div class="field row" style="width: 60%;">
    <div class="col-md-6" style="left: -20px;"><%= form.label :aprobada %></div>
    <div class="col-md-6"><%= form.check_box :aprobada, id: :promocion_aprobada %></div>
  </div>

  <div class="field row" style="width: 40%; padding: 15px;">
    <div class="col-md-6" style="left: -9px;"><% form.label :poster , class: 'oculto-casi'%></div>
    <div class="col-md-6"><% form.text_field :poster, {id: :promocion_poster, class: 'oculto-casi'}%></div>
  </div>

  <div class="field row" style="width: 40%; padding: 15px;">
    <div class="col-md-6" style="left: -115px;"><%= form.label :negocio_id %></div>
    <div class="col-md-6"><%=form.collection_select(:negocio_id, Negocio.all, :id,:nombre_empresa, prompt: "Selecciona la empresa que desees", class: 'grande_l') %></div>

  </div>
  <div class="actions">
    <%= form.submit("Aceptar", class: "btn-warning") %>
  </div>
<% end %>
</center>

app/views/promocions/edit.html.erb
<style>
.fBlanco{
	background: white;
}
.naranja1{
  color:orange;
  text-align: center;
  font-size: 400%;
}
.centrado{
	width: 100%;
	padding: 10%;
	padding-top: 0%;
	font-size: 140%;
}
.centrado label{
	color: #1E88E5;
}
.centrado input{
	margin: 1%;
	font-size: 130%;
	width: 50%;
}
.miClase{
	color:red;
}
.oculto-casi{
	display: none;
}
</style>


<body class = "fBlanco">

<h1 class = "naranja1">Editando Promocion</h1>

<section class ="centrado">
<%= render 'form', promocion: @promocion %>

<%= link_to 'Ver Promocion', @promocion %> |


<% if @promocion.aprobada ==1%>

  <%= link_to 'Regresar', promocions_path %>

  <%else%>
    <% if @promocion.aprobada ==-1%>
      <%= link_to 'Regresar',{:controller => "rechazados", :action => "promociones"} %>
    <%else%>
      <%= link_to 'Regresar',{:controller => "pendientes", :action => "index"} %>
    <%end%>
  <%end%>

</section>

</body>

app/views/promocions/index.html.erb
  <style>
    .amarillo{

  font-weight: bold;
  //background: yellow;
  font-size: 100%;
  float:right;
  clear: right;
}
.rojo{
  font-weight: bold;
  //background: red;
  font-size: 100%;
  float:right;
  clear: right;
}
#pArriba{
  margin-top: -20%
}
.ocultar{
margin-top:-20%;
margin: 0%
}
#elem{
  margin-top: -5%;
  margin-left: -15%;
}
#btIr{
  padding: 0%;
  margin:0%;
}
h1{
  clear: both;
}
#nombre{
    margin-left: 8%;
}
ul li span{
  float: left;
  margin-top: 1.5%;
}
#correo{
  margin-left: 10%;
}
#btIr{
  width: 15%;
  margin-top: 1%;
}
@media screen and (max-width: 800px){
#btIr{ float: right;
  margin-top: 3%;
  width: 30%;

}
.nuevo{
  border-radius: 5px;
}
}
.nuevo{
  font-weight: bold;
  font-size: 120%;
  margin-left: 40%;
  margin-right: 40%;
  width: 20%;
  margin-bottom: 3%;
  color: orange;
  background-color: orange;
  text-align: center;
}
.naranja{
  color: orange;
}
  </style>

  <header id="main-header">

    <a id="logo-header" class="ocultar" >
      <span class="site-name">Promociones Registradas</span>
      <span class="site-desc">Lista (por nombre de la promocion)</span>
    </a> <!-- / #logo-header -->

    <nav>
      <ul>
        <li id = "op4"><a><%= link_to "Usuarios", :controller => "users", :action => "index" %></a></li>
        <li id = "op4"><a><%= link_to "Negocios", :controller => "negocios", :action => "index" %></a></li>
        <li id = "op4"><a><%= link_to "Inicio", :controller => "inicio", :action => "opciones" %></a></li>
      </ul>
    </nav><!-- / nav -->

  </header>


<section >


    <article >
      <header>
        <div>
          <%=link_to "Promociones Pendientes", {controller: "pendientes"}, class: "amarillo"%>
          <%=link_to "Promociones Rechazadas y BAJAS", {controller: "rechazados", action: "promociones"}, class: "rojo"%>
        </div>
        <h1>PROMOCIONES VERIFICADAS Y ACTIVAS</h1>
      </header>
      <br><br><br><br>
        <ul>
          <% @promocions.each do |promocion| %>
          <li>
            <span id = "nombre"><%=promocion.nombre%> </span>
            <span id = "correo">Negocio: <%= promocion.negocio.nombre_empresa %></span>
            <button id = "btIr" >
              <%= link_to 'Eliminar',  promocion,method: :delete ,data: { confirm: 'Desea eliminar la promocion?' } %>
            </button>
            <button id = "btIr">
                    <%= link_to 'Ver Promocion', promocion %>
            </button>
          </li>
          <% end %>
        </ul>

    </article> <!-- /article -->

</section>


<label class = "nuevo"><%= link_to 'Nueva Promocion', new_promocion_path ,:class => "naranj"%></label>

app/views/promocions/new.html.erb
<style>
.fBlanco{
	background: white;
}
.naranja1{
  color:orange;
  text-align: center;
  font-size: 400%;
}
.centrado{
	width: 100%;
	padding: 10%;
	padding-top: 0%;
	font-size: 140%;
}
.centrado label{
	color: #1E88E5;
}
.centrado input{
	margin: 1%;
	font-size: 130%;
}
.miClase{
	color:red;
}
</style>



<body >
<br /><br />
<h1 >Alta de Promocion</h1>

<section class ="centrado">
<%= render 'form', promocion: @promocion %>

<button class= "btn-warning"><%= link_to 'Regresar', promocions_path %></button>

</section>

</body>

app/views/promocions/show.html.erb
<style>

  *{
  box-sizing: border-box;
  text-align: justify;
}
#main-header{
  padding-top: 0%;
  margin-top: -2%;
}
.fBlanco{
  background-color: white;
}
.nuevoUsuario{
  background-color: white;
  width: 90%;
  margin-left: 5%;
  margin-right: 5%;
  box-shadow: 0 0 10px rgba(0,0,0,.2);
  padding: 2%;
  margin-top: 2%;
}
.naranja{
  color:orange;
  text-align: center;
  margin: 0%;
  margin-top: -3%;
}
.botonesDecision{
  float: right;
  margin-left: 20%;
  width: 45%;
}
.cuerpoUsuario{
  clear: both;
  padding-top: 1.5%;
  margin-bottom: 27%;
  height: auto;
}
#btAceptar{
  margin-left: 25%;
  background-color: green;
}
#btRechazar{
  float: right;
  background-color: red;
}
.btUsu{
  text-align: center;
  color:white;
  border:none;
  border-radius: 3px;
  font-size: 110%;
  width: 30%;
  height: 30px;
}
#btAceptar:hover{
  border:2px;
  border-color: green;
  background-color: white;
  color: green;
  cursor: pointer;
  border: 2px solid green;
}
#btRechazar:hover{
  background-color: white;
  color: red;
  cursor: pointer;
  border: 2px solid red;
}
#fotoUsuario{
  margin-top: 1.6%;
  float: left;
  width: 35%;
  height: 400px;
  background-color: orange;
  padding: 10px;
}
#datosUsuario{
  float: left;
  width: 85%;
  margin-left: 5%;
  padding: 10px;
}
.etiquetas{
  font-size: 150%;
  float: left;
  clear: left;
  margin-bottom: 2%;
}
.cajita{
  margin-left: 5%;
  width: 95%;
  background-color: olive;
  padding: 0.5%;
}
/*
Para el cambio de los tamaños de las pantallas
*/
@media screen and (max-width: 1200px){
  #fotoUsuario{
  float: left;
  width: 35%;
  height: 360px;
  background-color: orange;
  padding: 10px;
}
}
@media screen and (max-width: 1100px){
  #fotoUsuario{
  margin-top: 1%;
  float: left;
  width: 35%;
  height: 360px;
  background-color: orange;
  padding: 10px;
}
#datosUsuario{
  margin-top: 1%;
  float: left;
  width: 85%;
  margin-left: 5%;
  padding: 10px;
}
}
@media screen and (max-width: 800px){
  #fotoUsuario{
  margin-top: 6%;
  float: left;
  width: 35%;
  height: 300px;
  background-color: orange;
  padding: 10px;
}

  .etiquetas{
    margin-top: 2%;
    margin-bottom: 2%;
  }
}
@media screen and (max-width: 500px){
  .botonesDecision{
    margin-top: 5%;
    float: none;
    width: 70%;
  }
  #btAceptar{
  margin-left: 12%;
  background-color: green;
  margin-right: 0%;
  }
  #btRechazar{
  background-color: red;
  float: none;
  margin-left: 0%;
  }
  .naranja{
    float: none;
    font-size: 160%;
  }
  #fotoUsuario{
  margin-top: 5%;
  float: none;
  width: 35%;
  margin-left: 32.5%;
  margin-right: 32.5%;
  height: 150px;
  background-color: orange;
  }
  #datosUsuario{
    margin-top: 2.5%;
  float: none;
  width: 100%;
  margin-left: 0%;
  padding: 10px;
  }
  .etiquetas{
    font-size: 100%;
  }
}
</style>



<p id="notice"><%= notice %></p>


<body >

<header id="main-header">

    <a id="logo-header" class="ocultar" >
      <span class="site-name">Promocion</span>
      <span class="site-desc"><%= @promocion.nombre %> </span>
    </a> <!-- / #logo-header -->

    <nav>
      <ul>
        <li id = "op4"><a><%= link_to "Inicio", :controller => "inicio", :action => "opciones" %></a></li>
      </ul>
    </nav><!-- / nav -->

  </header><!-- / #main-header -->



<section id = "nuevoUsuario">
  <article>
  <h1 class="naranja" >DATOS DE LA PROMOCION</h1>

  <div class = "cuerpoUsuario">

    <div id = "datosUsuario">

      <%begin%>
  <!--Aqui pongo el despliegue de la foto-->
  <!--Se logra gracias a lo que esta en el controlador-->
    <img src="/<%=@promocion.poster%>" width="50px">
    <br>
  <%rescue%>
  <%end%>


      <label class = "etiquetas">Promocion:</label>
      <a class = "etiquetas cajita"><%= @promocion.nombre %></a>
      <label class = "etiquetas">Descripcion</label>
      <a class = "etiquetas cajita"><%= @promocion.descripcion %></a>
      <label class = "etiquetas">Negocio:</label>
      <a class = "etiquetas cajita"><%= @promocion.negocio.nombre_empresa %></a>
      <label class = "etiquetas">Fecha de Registro:</label>
      <a class = "etiquetas cajita"> <%= @promocion.fecha_registro %> </a>
      <label class = "etiquetas">Activa:</label>
      <%if @promocion.aprobada==1%>
        <a class = "etiquetas cajita">Sí</a>
      <%else%>
        <a class = "etiquetas cajita">No</a>
      <%end%>
    </div>

  </div>
  </article>

</section>



<div id = "datosUsuario">
<%= link_to 'Editar', edit_promocion_path(@promocion) %>

<% if @promocion.aprobada ==1%>

  <%= link_to 'Regresar', promocions_path %>

  <%else%>
    <% if @promocion.aprobada ==-1%>
      <%= link_to 'Regresar',{:controller => "rechazados", :action => "promociones"} %>
    <%else%>
      <%= link_to 'Regresar',{:controller => "pendientes", :action => "index"} %>
    <%end%>
  <%end%>

<% if @promocion.aprobada ==-1%>

<br><br>
  <%= link_to 'Eliminar', @promocion, method: :delete, data: { confirm: 'Desea eliminar la promocion?' } %>
</div>

<%end%>



</body>