config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :promocions
  resources :llamadas
  resources :categorias
  resources :negocios
  resources :vendedors
  resources :venta
  resources :entrevistas
  resources :version_negocios

  root 'inicio#opciones'

  get 'inicio/opciones'

  get 'users/index'

  post 'users/new'

  post 'users/create'

  get 'rechazados/users'

  get 'rechazados/negocios'

  get 'rechazados/promociones'

  get 'pendientes/rechazados'

  get 'pendientes/index'

  get 'entrevistas/index'

  get 'entrevistas/new'

  get 'version_negocios/index'

  get 'version_negocios/destroy'


end

app/controllers/entrevistas_controller.rb
class EntrevistasController < ApplicationController


  # GET /vendedors
  # GET /vendedors.json
  def index
    #@vendedors = Vendedor.all.includes(:usuario)
    @vendedors = Vendedor.find_by_sql("SELECT v.*, u.* FROM  vendedors v, users u WHERE v.user_id = u.id");
    @usuarios = User.where(tipo: "v")
  end

  # GET /vendedors/1
  # GET /vendedors/1.json
  def show
    @usuario = User.find(@vendedor.user_id)
    #@vendidos = Ventum.where(vendedor_id: @usuario_id).includes(:usuarios)
    #cadSQL = "SELECT u.nombre_usuario, u.apellidos, u.celular, v.fecha_venta FROM Kali_Base.usuarios u, Kali_Base.venta v WHERE  v.vendedor_id = "+@vendedor.usuario_id.to_s;
    cadSQL = "SELECT u.nombre_usuario, u.apellidos, u.celular, v.fecha_venta FROM Kali_Base.usuarios u, Kali_Base.venta v WHERE v.user_id = u.id AND v.vendedor_id = "+(@vendedor.usuario_id.to_s) +" order by fecha_venta DESC";
    @vendidos = Ventum.find_by_sql(cadSQL);

    Dir.chdir "#{Rails.root.join('public/')}"

    #iteración de todos los usuarios en el arreglo @usuarios
      # creamos una variable que va a crear en string el nombre de la foto que se va a guardar
      # ej. user_image_23.png para el usuario con id 23
      saveName = "user_image_#{@usuario.id}.png"

      # abrimos el filestream para escritura con el nombre de la variable saveName
      fotoUsuario = File.open(saveName, 'wb') do |f|

      # el begin y rescue es el clásico try/catch
      begin
        # intentamos convertir los bytes que se reciben de la base de datos en encoding BASE64
        # y lo escribimos en el filestream usando decode64. Se guardaría en /public/user_image_23.png
        f.write(Base64.urlsafe_decode64(@usuario.foto))

        # cambiamos el contenido de la propiedad foto para que no sea el arreglo de bytes sino el
        # nombre con el que quedó guardado en /public/

        if  @promocion.poster != ""

        # cambiamos el contenido de la propiedad foto para que no sea el arreglo de bytes sino el
        # nombre con el que quedó guardado en /public/
        @usuario.foto=saveName

      else
        @usuario.foto="default_user_image.png"
      end

        # cerramos el stream
        f.close
      # si escribir la foto falla por algún motivo...
      rescue => ex
        # ignoramos lo que se haya jalado de la base de datos y ponemos de nombre una imagen genérica
        # esta imagen debe estar guardada eb /public/
        @usuario.foto="default_user_image.png"
      end
  end

  end

  # GET /vendedors/new
  def new
    @vendedor = Vendedor.new
  end

  # GET /vendedors/1/edit
  def edit
  end

  def entrevista

  end

  # POST /vendedors
  # POST /vendedors.json
  def create
    @vendedor = Vendedor.new(vendedor_params)

    respond_to do |format|
      if @vendedor.save
        format.html { redirect_to @vendedor, notice: 'Vendedor was successfully created.' }
        format.json { render :show, status: :created, location: @vendedor }
      else
        format.html { render :new }
        format.json { render json: @vendedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendedors/1
  # PATCH/PUT /vendedors/1.json
  def update
    respond_to do |format|
      if @vendedor.update(vendedor_params)
        format.html { redirect_to @vendedor, notice: 'Vendedor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendedor }
      else
        format.html { render :edit }
        format.json { render json: @vendedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendedors/1
  # DELETE /vendedors/1.json
  def destroy
    @vendedor.destroy
    respond_to do |format|
      format.html { redirect_to vendedors_url, notice: 'Vendedor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendedor
      @vendedor = Vendedor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendedor_params
      params.require(:vendedor).permit(:codigo, :user_id)
    end

    def check_if_user_active

    end
end

app/views/entrevistas/_form.html.erb
<%= form_with(model: vendedor, local: true) do |form| %>
  <% if vendedor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vendedor.errors.count, "error") %> prohibited this vendedor from being saved:</h2>

      <ul>
      <% vendedor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%=form.label :codigo %>
    <label>Escriba letras y numeros al azar, deben ser MAXIMO 6 digitos</label>
    <%= form.text_field :codigo, id: :vendedor_codigo %>
  </div>

  <div class="field dentro">
    <% form.label :user_id %>
    <label>Selecciona el usuario para hacerlo vendedor y darle su código</label>
    <br>
    <%=form.collection_select(:user_id, User.find_by_sql("
SELECT * FROM users WHERE users.tipo = 'v' AND id NOT IN(SELECT vendedors.user_id FROM vendedors);"), :id,:name_with_initial, prompt: "Selecciona al usuario que decidas darle su código de vendedor", class: 'grande_l') %>
  </div>

  <br>

  <div class="actions der">
    <%= form.submit("Aceptar") %>
  </div>
<% end %>

app/views/entrevistas/edit.html.erb
<h1>Editing Vendedor</h1>

<%= render 'form', vendedor: @vendedor %>

<%= link_to 'Show', @vendedor %> |
<%= link_to 'Back', vendedors_path %>

app/views/entrevistas/index.html.erb
<style>

  .centrado{
    margin-top: -3%;
    margin-bottom: 1%;
    font-size: 150%;
    text-align: center;
  }

  .amarillo{

  font-weight: bold;
  //background: yellow;
  font-size: 100%;
  float:right;
  clear: right;
}

.rojo{
  font-weight: bold;
  //background: red;
  font-size: 100%;
  float:right;
  clear: right;
}

#pArriba{
  margin-top: -20%
}

.ocultar{
margin-top:-20%;
margin: 0%
}

#elem{
  margin-top: -5%;
  margin-left: -15%;
}

#btIr{
  padding: 0%;
  margin:0%;
}

h1{
  clear: both;
}



#nombre{
    margin-left: 8%;
}

ul li span{
  float: left;
  margin-top: 1.5%;
}

#correo{
  margin-left: 10%;
}

#btIr{
  width: 15%;
  margin-top: 1%;
}

@media screen and (max-width: 800px){

#btIr{ float: right;
  margin-top: 3%;
  width: 30%;

}

.nuevo{

  border-radius: 5px;

}
}

.nuevo{
  font-weight: bold;
  font-size: 120%;
  margin-left: 40%;
  margin-right: 40%;
  width: 20%;
  margin-bottom: 3%;
  color: orange;
  background-color: orange;
  text-align: center;
}

.naranja{
  color: orange;
}


</style>

<header id="main-header">

    <a id="logo-header" class="ocultar" >
      <span class="site-name">Vendedores Registrados</span>
      <span class="site-desc">Lista</span>
    </a> <!-- / #logo-header -->

    <nav>
      <ul>
        <li id = "op4"><a><%= link_to "Regresar", :controller => "inicio", :action => "opciones" %></a></li>
      </ul>
    </nav><!-- / nav -->

  </header><!-- / #main-header -->



  <section >
    <br /><br />
      <article id = "primer">
        <header>
          <h1>USUARIOS DE TIPO VENDEDOR</h1>
        </header>
        <br><br><br><br><br><br>

          <ul>
            <% @usuarios.each do |usuario| %>
            <li>
              <span id = "nombre"><%=usuario.name%> <%=usuario.apellidos%></span>
              <span id = "correo">Correo: <%=usuario.email%></span>
              <button id = "btIr">
                      <%= link_to 'Ver Perfil', usuario %>
              </button>
            </li>
            <% end %>
          </ul>
      </article> <!-- /article -->

  </section>

  <section class = "centrado">

      <label class = "nuevo"><%= link_to 'Asignar codigo', new_vendedor_path %></label>
  </section>

app/views/entrevistas/new.html.erb
<style>

.fBlanco{
	background: white;
}


.naranja1{
  color:orange;
  text-align: center;
  font-size: 400%;

}

.centrado{
	width: 100%;
	padding: 10%;
	padding-top: 0%;
	font-size: 140%;
}

.centrado label{
	color: #1E88E5;
}

.centrado input{
	margin: 1%;
	font-size: 130%;
}


.miClase{
	color:red;
}

.dentro select{
	background-color: #FFF3E0;
	font-size: 100%;
}

.alad{
	margin-left: 30%;
}

.der{
	text-align: left;
	font-size: 120%;
}	

</style>


<body class = "fBlanco">

<h1 class = "naranja1">Alta de Vendedor</h1>

<section class ="centrado">

<%= render 'form', vendedor: @vendedor %>
<br>
<%= link_to 'Regresar', vendedors_path,:class => "alad" %>

<br><br>
<label>Si no encuentras a la persona que buscas, es porque primero debes ir a usuarios y cambiarle el tipo de usuarios a 'v'</label>

</section>

</body>

app/views/entrevistas/show.html.erb
<style>

#mapa{
    width: 100%;
    height: 500px;
  }

@media screen and (max-width: 700px){
  #mapa{
    width: 80%;
    height: 300px;
    margin: 10%;
    margin-top: 100%;
  }

  .ocultito{
    display: inline-block;
  }

}

#fBlanco{
  background-color: white;
}

.naranja{
  color: orange;
  font-weight: bold;

}

.arribita{
  margin-top:-5%;
  padding-top: 0%;
}

.arribita2{
  margin-top: 1%;
  padding-top: 10%;
}

.etiquetas{
  font-size: 150%;
  float: left;
  clear: left;
  text-align: left;
  margin-bottom: 2%;
}

.cajita{
  margin-left: 10%;
  width: 90%;
  background-color: orange;
  padding: 0.5%;
}

#otraCajita{
  width: 100%;
  text-align: center;
}

.ocultito{
  display: none;
}

.siempreOculto{
  display: none;
}



.fBlanco{
	background-color: white;
}


#btIr{
  margin-right: 20%;
  margin-top: 32%;
}

.white{
	color: white;
	font-weight: bold;
}

@media screen and (max-width: 800px){
    #btIr{
      margin-right: -10%;
      margin-top: 32%;
}
}

.naranja{
	margin-top: -1%;
}

.fNaranja{
	margin-top: 35%;
	clear: both;
	background-color: orange;
	width: 100%;
  height: auto;
}


@media screen and (min-width: 825px){


  .derecha{
    margin-right: -50%;
  }




}

#correo{
  float: left;
  clear: left;
}
#nombre{
  float: left;
  clear: left;
}

</style>

<body class = "fBlanco">

<header id="main-header">

    <a id="logo-header" class="ocultar" >
      <span class="site-name">Vendedor</span>
      <span class="site-desc">Historial</span>
    </a> <!-- / #logo-header -->

    <nav>
      <ul>

        <li id = "op4"><a><%= link_to "Vendedores", :controller => "vendedors", :action => "index" %></a></li>
      </ul>
    </nav><!-- / nav -->

  </header>


  <section id = "nuevoUsuario">
  <article>
  <h1 class="naranja" >DATOS DEL VENDEDOR</h1>

  <div class = "cuerpoUsuario">

    <div id = "datosUsuario">

      <%begin%>
  <!--Aqui pongo el despliegue de la foto-->
  <!--Se logra gracias a lo que esta en el controlador-->
    <img src="/<%=@usuario.foto%>" width="50px">
    <br>
  <%rescue%>
  <%end%>

      <label class = "etiquetas">Nombre</label>
      <a class = "etiquetas cajita"><%= @usuario.nombre_usuario %></a>
      <label class = "etiquetas">Apellidos</label>
      <a class = "etiquetas cajita"><%= @usuario.apellidos %></a>
      <label class = "etiquetas">Correo electrónico</label>
      <a class = "etiquetas cajita"><%= @usuario.correo %></a>
      <label class = "etiquetas">Teléfono</label>
      <a class = "etiquetas cajita"> <%= @usuario.celular %> </a>
      <label class = "etiquetas">Activo</label>
      <%if @usuario.activo%>
        <a class = "etiquetas cajita">Sí</a>
      <%else%>
        <a class = "etiquetas cajita">No</a>
      <%end%>
    </div>

  </div>
  </article>

</section>

<section class = "fNaranja">
	<!--Aqui se despliega la fecha de la venta, el nombre de la persona a la que se refirió-->
	<article>
  		<h1 class = "white" >VENTAS REALIZADAS</h1>

      <br><br><br><br><br>

  		<ul>
          <% @vendidos.each do |usuario| %>
          <li>
            <span id = "nombre"><%=usuario.nombre_usuario%> <%=usuario.apellidos%></span>
            <span id = "correo">Celular: <%=usuario.celular%> Fecha: <%=usuario.fecha_venta%></span>
          </li>
          <% end %>
        </ul>
  	</article>
</section>



<!--
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @vendedor.codigo %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @vendedor.usuario %>
</p>

<%= link_to 'Edit', edit_vendedor_path(@vendedor) %> |
<%= link_to 'Back', vendedors_path %>-->
</body>