config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :promocions
  resources :llamadas
  resources :categorias
  resources :negocios
  resources :vendedors
  resources :venta
  resources :entrevistas
  resources :version_negocios

  root 'inicio#opciones'

  get 'inicio/opciones'

  get 'users/index'

  post 'users/new'

  post 'users/create'

  get 'rechazados/users'

  get 'rechazados/negocios'

  get 'rechazados/promociones'

  get 'pendientes/rechazados'

  get 'pendientes/index'

  get 'entrevistas/index'

  get 'entrevistas/new'

  get 'version_negocios/index'

  get 'version_negocios/destroy'


end

app/models/negocio.rb
class Negocio < ApplicationRecord
  belongs_to :user
	has_many :negocio_palabra
	has_many :categoria
  has_many :palabra_clave, :through => :negocio_palabra
  has_many :categoria, :through => :negocio_categoria
  has_many :promocion
  has_many :comentarios
  has_many :horario
  has_many :llamada
  has_many :pendiente
  belongs_to :membresia, class_name: "Membresium"
end

app/controllers/negocios_controller.rb
class NegociosController < ApplicationController
  before_action :set_negocio, only: [:show, :edit, :update, :destroy]


  # GET /negocios
  # GET /negocios.json
  def index
    if params[:search]
      @negocios = Negocio.where("nombre_empresa LIKE ?", "%#{params[:search]}%").includes(:user).where(verificado: 1)
    elsif params[:order]
      @negocios = Negocio.all.includes(:user).order(:fecha_registro).where(verificado: 1)
    elsif params[:basico]
      @negocios = Negocio.where("membresia_id LIKE 1", "%#{params[:search]}%").includes(:user).where(verificado: 1)
    elsif params[:gratis]
      @negocios = Negocio.where("membresia_id LIKE 2", "%#{params[:search]}%").includes(:user).where(verificado: 1)
    elsif params[:premium]
      @negocios = Negocio.where("membresia_id LIKE 3", "%#{params[:search]}%").includes(:user).where(verificado: 1)
    else
      @negocios = Negocio.all.includes(:user).where(verificado: 1)
    end


    #cambiar al directorio /public
    Dir.chdir "#{Rails.root.join('public')}"

    #iteración de todos los usuarios en el arreglo @usuarios
    @negocios.each do |n|
      # creamos una variable que va a crear en string el nombre de la foto que se va a guardar
      # ej. user_image_23.png para el usuario con id 23
      saveName = "business_image_#{n.id}.png"

      # abrimos el filestream para escritura con el nombre de la variable saveName
      fotoNegocio = File.open(saveName, 'wb') do |f|

      # el begin y rescue es el clásico try/catch
      begin
        # intentamos convertir los bytes que se reciben de la base de datos en encoding BASE64
        # y lo escribimos en el filestream usando decode64. Se guardaría en /public/user_image_23.png
        f.write(Base64.urlsafe_decode64(n.imagen))

        # cambiamos el contenido de la propiedad foto para que no sea el arreglo de bytes sino el
        # nombre con el que quedó guardado en /public/
        n.imagen=saveName

        # cerramos el stream
        f.close

      # si escribir la foto falla por algún motivo...
      rescue => ex
        # ignoramos lo que se haya jalado de la base de datos y ponemos de nombre una imagen genérica
        # esta imagen debe estar guardada eb /public/
        n.imagen="default_user_image.png"
      end
    end
  end

  end

  # GET /negocios/1
  # GET /negocios/1.json
  def show
     Dir.chdir "#{Rails.root.join('public/')}"

    #iteración de todos los usuarios en el arreglo @usuarios
      # creamos una variable que va a crear en string el nombre de la foto que se va a guardar
      # ej. user_image_23.png para el usuario con id 23
      saveName = "business_image_#{@negocio.id}.png"

      # abrimos el filestream para escritura con el nombre de la variable saveName
      fotoUsuario = File.open(saveName, 'wb') do |f|

      # el begin y rescue es el clásico try/catch
      begin
        # intentamos convertir los bytes que se reciben de la base de datos en encoding BASE64
        # y lo escribimos en el filestream usando decode64. Se guardaría en /public/user_image_23.png
        f.write(Base64.urlsafe_decode64(@negocio.imagen))

        # cambiamos el contenido de la propiedad foto para que no sea el arreglo de bytes sino el
        # nombre con el que quedó guardado en /public/
        @negocio.imagen=saveName

        # cerramos el stream
        f.close
      # si escribir la foto falla por algún motivo...
      rescue => ex
        # ignoramos lo que se haya jalado de la base de datos y ponemos de nombre una imagen genérica
        # esta imagen debe estar guardada eb /public/
        @negocio.imagen="default_user_image.png"
      end
  end
  end

  # GET /negocios/new
  def new
    @negocio = Negocio.new

  end

  # GET /negocios/1/edit
  def edit

  end

  # POST /negocios
  # POST /negocios.json
  def create

    if negocio_params[:imagen] == nil
      base64 = ""
    elsif negocio_params[:imagen] == ""
      base64 = ""
    else
      base64 = negocio_params[:imagen]
      base64.slice!('data:image/png;base64,')
    end

    @negocio = Negocio.new(negocio_params)

    respond_to do |format|
      if @negocio.save

        format.html { redirect_to @negocio, notice: 'Negocio was successfully created.' }
        format.json { render :show, status: :created, location: @negocio }
      else
        format.html { render :new }
        format.json { render json: @negocio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /negocios/1
  # PATCH/PUT /negocios/1.json
  def update
    respond_to do |format|
      if @negocio.update(negocio_params)
        format.html { redirect_to @negocio, notice: 'Negocio was successfully updated.' }
        format.json { render :show, status: :ok, location:@negocio}
      else
        format.html { render :edit }
        format.json { render json: @negocio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /negocios/1
  # DELETE /negocios/1.json
  def destroy
    @negocio.update(:verificado => -1)
    respond_to do |format|
      format.html { redirect_to negocios_url, notice: 'Negocio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_negocio
      @negocio = Negocio.find(params[:id])
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def negocio_params
      params.require(:negocio).permit(:nombre_empresa, :latitud, :longitud, :verificado, :precio_promedio, :rating_precio, :rating_calidad, :imagen, :cantidad_rating, :cantidad_precio, :ultima_conexion, :fecha_registro, :user_id, :veces_visto, :membresia_id, :telefono, :descripcion)
    end


end

app/views/negocios/_form.html.erb
<script>
function readFile(input) {

    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (event) {
        $profilePicPreview.croppie('bind', {
          url: event.target.result
        });
      };
      reader.readAsDataURL(input.files[0]);
      document.getElementById('imageFileName').value = input.files[0].name
    } else {
      alert('Sorry - you\'re browser doesn\'t support the FileReader API');
    }

}
function saveResult(input){
    /*$profilePicPreview.croppie('result', 'canvas').then(function (resp) {
         $('#result-image').attr('src', resp);
         $('#result-image').css('width', '130px');
         $('#result-image').css('height', '130px');
    });*/

    $profilePicPreview.croppie('result', 'base64').then(function (resp) {
        document.getElementById('base64string').value = resp;
    });
}
</script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    crossorigin="anonymous" />
<%= form_with(model: negocio, local: true) do |form| %>
  <% if negocio.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(negocio.errors.count, "error") %> prohibited this negocio from being saved:</h2>

       <ul>
       <% negocio.errors.full_messages.each do |message| %>
         <li><%= message %></li>
      <% end %>
      </ul>
    </div>
   <% end %>
   <br /><br />
   <div class="field row" style="width: 100%;">
       <div class="col-md-6"><%= form.label :nombre_empresa %></div>
       <div class="col-md-6" style="left: -260px;bottom: 10px;"><%= form.text_field :nombre_empresa, id: :negocio_nombre_empresa %></div>
   </div>

  <div class="row">
     <div class="col-xs-8 col-sm-10 padding-right-0">
        <input id="autocomplete"  onfocus="geolocate()" type="text" class="form-control kali-input-smpan">
     </div>
     <div class="col-xs-4 col-sm-2 padding-left-0">
        <button type="button" class="btn btn-block kali-btn-primario" onclick="useLocation()"><i id="find-me-icon" class="fa fa-location-arrow" style="color: #3763A2;"></i></button>
     </div>
     <!-- detalles de la dirección (oculto) -->
     <div style="display: none">
				<div class="row">
	          <div class="col-xs-12 col-sm-6">
	              <div class="form-group">
				      			<label for="latbox">Lat</label>
                       <%= form.text_field :latitud, id:'geometry.location.lat'%>
                </div>
           </div>
	         <div class="col-xs-12 col-sm-6">
	             <div class="form-group">
	                 <label for="lngbox">Lng</label>
	                    <%= form.text_field :longitud, id:'geometry.location.lng' %>
	             </div>
	         </div>
	      </div>
    </div>
     <!-- /detalles de la dirección (oculto) -->
  </div>
  <br />
  <div class="row">
     <div class="col-xs-12">
        <div id="map"></div>
     </div>
  </div>
<br />
<br />
  <label style="left: -20px;">Desmarque si quiere dar de Baja</label>
  <br />
  <div class="field row" style="width: 60%;">
    <br />
    <div class="col-md-6"><%= form.label :verificado %></div>
    <div class="col-md-6"><%= form.check_box :verificado, id: :negocio_verificado %></div>
  </div>

  <div class="input-group">
      <label class="input-group-btn">
          <span class="btn kali-btn-browse">
              Elige una imagen<input type="file" id="profile-picture-upload" style="display: none;">
          </span>
      </label>
      <input type="text" id="imageFileName" class="form-control kali-input kali-file-input" style="font-size: 10px;" readonly>
      <%= form.text_field( :imagen, id: :negocio_imagen, class:'form-control kali-input-sm', style: 'display:none;') %>
  </div>

<br />
  <div class="field mem">
      <div class="col-md-6" style="left: -9px;"><%= form.label :usuario_id%></div>
      <div class="col-md-6" style="left: -253px;"><%=form.collection_select(:user_id, User.all, :id,:name_with_initial, prompt: "Selecciona al usuario que decidas", class: 'grande_l') %></div>
  </div>

<br /><br />
  <div class="field mem">
    <div class="col-md-6" style="left: -9px;"><%= form.label :membresia_id%></div>
    <div class="col-md-6" style="left: -253px;"><%=form.collection_select(:membresia_id, Membresium.all, :id,:nombre, prompt: "Selecciona la membresia que decidas", class: 'grande_l') %></div>
  </div>
<br /><br />
  <div class="field">
    <div class="col-md-6" style="left: -9px;"><%= form.label :telefono %></div>
    <div class="col-md-6" style="left: -253px;"><%= form.text_field :telefono, {id: :negocio_telefono} %></div>
  </div>
<br />
  <div class="field">
    <div class="col-md-6" style="left: -9px;"><%= form.label :descripcion %></div>
    <div class="col-md-6" style="left: -253px;"><%= form.text_field :descripcion, {id: :negocio_descripcion} %></div>
  </div>
<br /><br />
<center>
  <div class="actions">
    <%= form.submit("ACEPTAR") %>
  </div>
</center>

<% end %>

app/views/negocios/_form_edit.html.erb
<header class="header">

<div class="container-fluid">

	<div class="row">


</div>
</header>



	<%= form_with(model: negocio, local: true) do |form| %>
	  <% if negocio.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(negocio.errors.count, "error") %> prohibited this negocio from being saved:</h2>

	      <ul>
	      <% negocio.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	  <div class="container-fluid">
	  	<div class="row">
	  		<div class="col-md-12">
	  			<h3>
	  				Registro
	  			</h3>
	  			<div class="row">
	  				<div class="col-md-6">
	  					<div class="form-group">

	  				    <%= form.text_field :nombre_empresa, id: :negocio_nombre_empresa, placeholder: "Nombre público de la empresa" %>
	  				  </div>
           		<br>

	  					<div class="form-group">

	  				  </div>
	  					<br>
	  					<div class="form-group">

	              <%= form.text_field :descripcion, id: :negocio_descripcion , placeholder: "Descripción"%>
	  				  </div>
	  					<br>


	          </div>

						<div class="row">
						<div class="col-md-12">

							<div class="row">

	  						<div class="col-md-6">

	  							<button type="button" class="btn btn-default">
	  								<%= link_to "Regresar", :controller => "negocios", :action => "index" %>
	  							</button>
	  						</div>
	  						<div class="col-md-6">
	                <div class="actions">

	                  <%=form.submit ("Modificar")%>
	                </div>
	  						</div>
	  					</div>
						</div>
					</div>
	  		</div>
	  	</div>
	  </div>
	</div>


<% end %>

app/views/negocios/index.html.erb
<style>
@media screen and (max-width: 1200px){
  #derecha{
    margin-left: 20%;
    width: 100%;
  }
  #btIr{
    margin-right: -35%;
    margin-top: 45%;
  }
}
@media screen and (min-width: 1200px){
  #derecha{
    margin-left: 10%;
    width: 100%;
  }
  //ajustar el boton de ver la empresa
  #btIr{
    margin-right: 50%;
  }
}
@media screen and (min-width: 1500px){
  #derecha{
    margin-left: 10%;
    width: 100%;
  }
}
.amarillo{
  font-weight: bold;
  background: orange;
  font-size: 100%;
  float:right;
  clear: right;
}
.rojo{
  font-weight: bold;
  background: orange;
  font-size: 100%;
  float:right;
  clear: right;
}
h1{
  clear: both;
}
@media screen and (max-width: 800px){
  .amarillo{
    float: left;
    margin-left: -8%;
  }
  .rojo{
    margin-bottom: 15%;
    clear: none;
    margin-right: -8%;
  }
  .op3{
    display: none;
  }
}
#btIr{
  padding: 0%;
  margin:0%;
}
h1{
  clear: both;
}
#nombre{
    margin-left: 8%;
}
ul li span{
  float: left;
  margin-top: 1.5%;
}
#correo{
  margin-left: 10%;
}
#btIr{
  width: 15%;
  margin-top: 1%;
}
@media screen and (max-width: 800px){
#btIr{ float: right;
  margin-top: 3%;
  width: 30%;
}
.nuevo{
  border-radius: 5px;
}
}
.nuevo{
  font-weight: bold;
  font-size: 120%;
  margin-left: 40%;
  margin-right: 40%;
  width: 20%;
  margin-bottom: 3%;
  color: orange;
  background-color: orange;
  text-align: center;
}
</style>

<section>

  <header id="main-header">

    <a id="logo-header" class="ocultar" >
      <span class="site-name">Negocios Registrados</span>
      <span class="site-desc">Lista (por nombre del negocio)</span>
    </a> <!-- / #logo-header -->

    <nav>
      <ul>
        <li id = "op4"><a><%= link_to "Usuarios", :controller => "users", :action => "index" %></a></li>
        <li style="background-color:#1E88E5;" id = "op4"><a><%= link_to "Promociones", :controller => "promocions", :action => "index" %></a></li>
        <li id = "op3"><a><%= link_to "Inicio", :controller => "inicio", :action => "opciones" %></a></li>
      </ul>
    </nav><!-- / nav -->

  </header>

    <article id = "primer">
      <header>
        <br><br><br><br><br>
        <div>
          <button type="button" class="btn btn-warning">
                  <%=link_to "Negocios Pendientes", {controller: "pendientes"}, class: "amarillo"%>
          </button>
          <button type="button" class="btn btn-warning">
                  <%=link_to "Negocios Rechazados y BAJAS", {controller: "rechazados", action: "negocios"}, class: "rojo"%>
          </button>
          <button type="button" class="btn btn-warning">
                  <%=link_to "Solicitud de cambios al negocio", {controller: "version_negocios", action: "index"}, class: "rojo"%>
          </button>
        </div>
        <br /><br />
        <h1>NEGOCIOS VERIFICADOS ACTIVOS</h1>
        <br />
        <%= form_tag("/negocios", :method => "GET", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Buscar"%>
            <%= submit_tag "Buscar", :name => nil , class: "btn btn-warning"%>
        <% end %>
        <br /><br>

          <%= form_tag("/negocios", :method => "GET", id: "order-form") do  %>
            <%= text_field_tag :order, params[:order], class: "orderhidden"%>
        <div style="left:-50px;">
            <%= submit_tag "Ordenar por fecha de registro", :name => nil, class: "btn btn-warning" %>
          <% end %>
        </div>
          <%= form_tag("/negocios", :method => "GET", id: "gratis-form") do %>
              <%= text_field_tag :gratis, params[:gratis], class: "orderhidden"%>
          <div style="left:-50px;">
              <%= submit_tag "Gratis", :name => nil , class: "btn btn-warning"%>
          <% end %>
          </div>
          <br />
          <%= form_tag("/negocios", :method => "GET", id: "basico-form") do %>
              <%= text_field_tag :basico, params[:basico], class: "orderhidden"%>
              <div style="left:-50px;">
                  <%= submit_tag "Basico", :name => nil, class: "btn btn-warning" %>
              <% end %>
              </div>
          <br />
          <%= form_tag("/negocios", :method => "GET", id: "premium-form") do %>
              <%= text_field_tag :premium, params[:premium], class: "orderhidden"%>
              <div style="left:-50px;">
                  <%= submit_tag "Premium", :name => nil, class: "btn btn-warning" %>
              <% end %>
              </div>

      </header>
      <br><br><br><br><br><br><br>

        <ul>
          <% @negocios.each do |negocio| %>
          <li>
            <span id = "nombre">Negocio: <%=negocio.nombre_empresa%></span>
            <span id = "correo">Dueño: <%= negocio.user.name %> <%= negocio.user.apellidos %></span>
            <button class="btn-danger" id = "btIr" >
              <%= link_to 'Eliminar',  negocio,method: :delete ,data: { confirm: 'Desea mandar el negocio a rechazados?' } %>
            </button>
            <button class= "btn-success" id = "btIr">
                    <%= link_to 'Ver Perfil', negocio %>
            </button>
          </li>
          <% end %>
        </ul>
    </article> <!-- /article -->

</section>

<label class = "nuevo"><%= link_to 'Nuevo Negocio', new_negocio_path ,:class => "naranja"%></label>